services:
  tracking-db:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: earthisflat123
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
